### PR TITLE
Add 7.1 and 7.2 dockerfiles

### PR DESCRIPTION
**Pull request by benyanke**
This allows both versions to coexist.

By updating your docker build config, you can have each one feed a tag on your build:

image

### CODE REVIEW

**Comment by benyanke** [comment]
Resolves #1

**Comment by benyanke** [comment]
I'd also recommend, while you're there, to add ubuntu as a base for autorebuild, to track security patches, if it isn't already.

image

**Comment by vcarreira** [comment]
Thanks Ben. I only saw the PR after doing the changes for PHP 7.2. I've tried to do a manual conflict resolution but things get worse :) So I've revert the last two commits to be able to merge your pull request and keep the proper kudos. 

Thanks again for your valuable contribution regarding the docker hub stuff. I'm just using this for my own personal projects so I'm not a docker / devops savvy guy.

**Comment by benyanke** [comment]
Excellent - I've been doing quite a bit of work with this, getting it working well for me. I may submit some bigger PRs in the future once I have mine working well.For example, on the FPM container, I now have the ability to run an arbitrary shell script on container up, so that you can run things like composer install, and edit it without rebuilding the container.

**Pull request merged**
